// Optimal SVGO configuration for musical notation SVG
// Generated by Incremental SVGO Test Framework
// Original size: 3,100,574 bytes
// Optimized size: 2,711,319 bytes  
// Size reduction: 12.6%
// Working plugins: 6/35

module.exports = {
  plugins: [
    "removeDoctype",
    "cleanupNumericValues",
    "moveGroupAttrsToElems",
    "collapseGroups",
    "convertPathData",
    "convertTransform"
],
  multipass: true
};
