// Optimal SVGO configuration for musical notation SVG
// Generated by Incremental SVGO Test Framework
// Original size: 3,100,574 bytes
// Optimized size: 2,504,279 bytes  
// Size reduction: 19.2%
// Working plugins: 9/35

module.exports = {
  plugins: [
    "removeDoctype",
    "minifyStyles",
    "cleanupNumericValues",
    "convertShapeToPath",
    "moveGroupAttrsToElems",
    "collapseGroups",
    "convertPathData",
    "convertTransform",
    "mergePaths"
],
  multipass: true
};
